CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(180) UNIQUE NOT NULL,
 mobile VARCHAR(30),
 password_hash TEXT NOT NULL,
 language VARCHAR(10) DEFAULT 'en',
 role VARCHAR(20) DEFAULT 'user',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS life_events (
 id SERIAL PRIMARY KEY,
 slug VARCHAR(80) UNIQUE NOT NULL,
 name VARCHAR(150) NOT NULL,
 category VARCHAR(80) NOT NULL,
 icon VARCHAR(50),
 description TEXT,
 duration VARCHAR(50),
 documents JSONB DEFAULT '[]',
 steps JSONB DEFAULT '[]',
 departments JSONB DEFAULT '[]',
 portal JSONB DEFAULT '[]',
 questions JSONB DEFAULT '[]',
 sources JSONB DEFAULT '[]',
 last_verified_at DATE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journeys (
 id SERIAL PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 event_id VARCHAR(80) NOT NULL,
 completed_steps JSONB DEFAULT '[]',
 answers JSONB DEFAULT '[]',
 status VARCHAR(20) DEFAULT 'active',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reminders (
 id SERIAL PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 title VARCHAR(180) NOT NULL,
 due_at TIMESTAMP NOT NULL,
 notes TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vault_documents (
 id SERIAL PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 category VARCHAR(80),
 name VARCHAR(255),
 mime_type VARCHAR(120),
 size_bytes INTEGER,
 storage_path TEXT,
 checksum VARCHAR(128),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
